#include <rtthread.h>
#include "generated/autoconf.h"

#ifdef CONFIG_TRUSTZONE
#define ARM_CM33_ENABLE_TRUSTZONE
#endif

#ifdef CONFIG_RT_USING_FINSH
#define RT_USING_FINSH
#endif

#define RT_THREAD_PRIORITY_MAX      CONFIG_RT_THREAD_PRIORITY_MAX
#define RT_TICK_PER_SECOND          CONFIG_RT_TICK_PER_SECOND
#define RT_ALIGN_SIZE               CONFIG_RT_ALIGN_SIZE
#define RT_NAME_MAX                 CONFIG_RT_NAME_MAX

#ifdef CONFIG_RT_USING_COMPONENTS_INIT
#define RT_USING_COMPONENTS_INIT
#endif

#ifdef CONFIG_RT_USING_USER_MAIN
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE   CONFIG_RT_MAIN_THREAD_STACK_SIZE
#endif

#ifdef CONFIG_RT_DEBUG
#define RT_DEBUG
#define RT_DEBUG_INIT               CONFIG_RT_DEBUG_INIT
#ifdef CONFIG_RT_USING_OVERFLOW_CHECK
#define RT_USING_OVERFLOW_CHECK
#endif
#endif

#ifdef CONFIG_RT_USING_HOOK
#define RT_USING_HOOK
#endif

#ifdef CONFIG_RT_USING_IDLE_HOOK
#define RT_USING_IDLE_HOOK
#endif

#ifdef CONFIG_RT_USING_TIMER_SOFT
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO       CONFIG_RT_TIMER_THREAD_PRIO
#define RT_TIMER_THREAD_STACK_SIZE CONFIG_RT_TIMER_THREAD_STACK_SIZE
#endif

#ifdef CONFIG_RT_USING_SEMAPHORE
#define RT_USING_SEMAPHORE
#endif

#ifdef CONFIG_RT_USING_MUTEX
#define RT_USING_MUTEX
#endif

#ifdef CONFIG_RT_USING_EVENT
#define RT_USING_EVENT
#endif

#ifdef CONFIG_RT_USING_MAILBOX
#define RT_USING_MAILBOX
#endif

#ifdef CONFIG_RT_USING_MESSAGEQUEUE
#define RT_USING_MESSAGEQUEUE
#endif

#ifdef CONFIG_RT_USING_HEAP
#define RT_USING_HEAP
#endif

#ifdef CONFIG_RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM
#endif

#ifdef CONFIG_RT_USING_TINY_SIZE
#define RT_USING_TINY_SIZE
#endif

#ifdef CONFIG_RT_USING_MEMTRACE
#define RT_USING_MEMTRACE
#endif

#ifdef CONFIG_RT_USING_CONSOLE
#define RT_USING_CONSOLE
#define RT_CONSOLEBUF_SIZE         CONFIG_RT_CONSOLEBUF_SIZE
#endif

#ifdef CONFIG_RT_USING_FINSH
#define RT_USING_FINSH
#define FINSH_THREAD_PRIORITY      (RT_THREAD_PRIORITY_MAX / 8 * CONFIG_RT_FINSH_THREAD_PRIORITY + 1)
#define FINSH_THREAD_STACK_SIZE    CONFIG_RT_FINSH_THREAD_STACK_SIZE
#define FINSH_HISTORY_LINES        CONFIG_RT_FINSH_HISTORY_LINES

#ifdef CONFIG_RT_FINSH_USING_SYMTAB
#define FINSH_USING_SYMTAB
#endif

#ifdef CONFIG_RT_FINSH_USING_DESCRIPTION
#define FINSH_USING_DESCRIPTION
#endif
#endif